default: &default
  adapter: postgresql
  host: localhost

development:
  <<: *default
  database: image_resizer_development
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['RAILS_MAX_THREADS'] %>

test:
  <<: *default
  database: image_resizer_test

production:
  <<: *default
  database: image_resizer_production
  username: image_resizer
  password: <%= ENV['IMAGE_RESIZER_DATABASE_PASSWORD'] %>
